### ISSUE TITLE
Connecting is unstable

### ISSUE THREAD

**Issue by ChillerDragon** [gerdoe-jr/tw-econ#8]
I get this error like 2/3 times when I connect to localhost

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoResponse', src/main.rs:21:117
```

**Comment by gerdoe-jr** [comment]
@ChillerDragon check it now

**Comment by ChillerDragon** [comment]
Yay panic is gone! And i can even run commands and see logs. Sadly I have like a ~1 minute delay. Not sure if thats some firewall or something else in my setup. But I guess laggy/slow is something else than unstable. So this issue is solved :)

**Comment by pmakin** [comment]
Happy ending
